# Change these first
owner: guillermodep # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Pichincha Portal Inicio
    url: https://inicio.pichincha.com/portal/inicio
  - name: Pichincha Cuenta Simple
    url: https://cuentasimple.pichincha.com/electronico?utm_source=portal&utm_medium=referral&utm_campaign=cuentasimple&utm_content=btn_home_abrir_cuenta
  - name: Pichincha Banca Web
    url: https://bancaweb.pichincha.com/
  - name: Pichincha Cash Management
    url: https://www.pichincha.com/loginNR/#/loginNR/auth/login
  - name: Pichincha Tarjetas
    url: https://inicio.pichincha.com/portal/servicios-web-tarjetas
  - name: Pichincha Credito Preciso
    url: https://creditoenlinea.pichincha.com/autogestion/login/?utm_source=portal&utm_medium=referral&utm_campaign=preciso&utm_content=btn_acceso_preciso
  - name: Pichincha 4U Portal
    url: https://4u.pichincha.com/auth/ingreso
  - name: Ilolay German
    url: https://ilolay.com.ar/es

assignees:
  - guillermodep

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: 
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Guille URL Status
  introTitle: "Verificaciçon de URLs Públicas"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
